### ISSUE TITLE
Unable to make demo work

### ISSUE THREAD

**Issue by cFreed-AKA-Alf** [tonystar/drupal-atoms#22]
Interested by this module, I followed steps stated in the "Demo" paragraph of the project page.
But enable Atoms defaults is impossible since the jQuery_update module is missing!

**Comment by TolstoyDotCom** [comment]
There's some sort of bug at the test site that causes it to skip the last modules in the list or similar. I tried a few times to change the URL without luck:

https://simplytest.me/project/drupal/7.32?patch[]=https://www.drupal.org/files/issues/field-schema-alter-691932-92.patch&add[]=treeable&add[]=views&add[]=atoms&add[]=entityreference_live_preview&add[]=references_dialog&add[]=jquery_update&add[]=features&add[]=ctools&add[]=entity&add[]=eck&add[]=entityreference&add[]=treeable&add[]=treeable

The core patch and the fact that the demo doesn't work will probably lead to a lot of people not even trying to get this to work.

**Comment by cFreed-AKA-Alf** [comment]
With the url you posted above, jquery_update module is well loaded... but this time entityreference is missing! Though it's present in the url...

**Comment by tonystar** [comment]
This problem is caused nor by link, nor by `atoms`.

It has several roots:

1. `entityreference_live_preview` module was changed and now depends on `jquery_update`.
2. So now `atoms` has 11 dependencies in total.
3. simplytest.me project limits the number of additional projects to 10, that's why the last one is not downloaded.

I submitted the request to increase this limit: https://www.drupal.org/node/2505927.
**Please put "+1" there to force the request!**

I'm also working on the `atomic` distribution project to simplify demo and installation.

**Comment by tonystar** [comment]
Hooray! The maintainer of `simplytest.me` raised the limit!

Checkout the demo now: http://drupal.tonystar.me/atoms/demo. Should work!

**Comment by cFreed-AKA-Alf** [comment]
Good news! Thanks, I'll test again soon.
